### Topics Covered
1. Import pandas
2. Rading CSV with read_csv, ease of using pandas read_csv vs native python's csv module.
3. DataFrames the backbone of pandas. 
4. df.shape for checking raws and columns.
5. df.info() for understanding more about data.
6. Pandas setting to read coustumized number of raws and columns in a DataFrame.
    - pd.set_option('display.max_columns', number of columns you want to see)
    - pd.set_option('display.max_raws', number of raws you want to see)
7. df.haed()
8. Isponce video add

In [16]:
import pandas as pd

In [14]:
path = r"E:\Project\Anaconda\csv\stackoverflow\survey_results_public.csv"
job_candidates = r"E:\Project\Anaconda\csv\csv\job_candidates"
df = pd.read_csv(path)

In [15]:
df

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64456,64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64457,64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64458,64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64459,64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,...,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
64460,65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [4]:
df.head(50)

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
5,6,I am a developer by profession,No,NaN,14,NaN,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
7,8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
8,9,I am a developer by profession,No,30.0,20,NaN,NaN,NaN,Tunisia,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular.js,jQuery,Just as welcome now as I felt last year,50.0,6,4
9,10,I am a developer by profession,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,...,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4
10,11,I am a developer by profession,Yes,23.0,13,Yearly,31000.0,40070.0,United Kingdom,Pound sterling,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Django;React.js,Angular;Angular.js;Django;React.js,Just as welcome now as I felt last year,40.0,10,2
11,12,I am a developer by profession,No,49.0,42,Monthly,1100.0,14268.0,Spain,European Euro,...,Easy,Appropriate in length,No,Mathematics or statistics,ASP.NET;jQuery,ASP.NET;jQuery,Just as welcome now as I felt last year,40.0,7,7
12,13,"I am not primarily a developer, but I write co...",Yes,53.0,14,Monthly,3000.0,38916.0,Netherlands,European Euro,...,Neither easy nor difficult,Too long,No,NaN,NaN,NaN,A lot less welcome now than last year,36.0,35,20
13,14,I am a developer by profession,Yes,27.0,13,Yearly,66000.0,66000.0,United States,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1
14,15,I am a student who is learning to code,Yes,NaN,13,NaN,NaN,NaN,France,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,4,NaN
15,16,I am a developer by profession,Yes,45.0,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23
16,17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
17,18,I am a developer by profession,Yes,32.0,12,Monthly,105000.0,1260000.0,United States,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12
18,19,I am a developer by profession,No,24.0,15,Yearly,83400.0,83400.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Express;React.js,Angular;Angular.js;ASP.NET Core,Just as welcome now as I felt last year,35.0,9,3
19,20,I am a developer by profession,Yes,40.0,18,NaN,NaN,NaN,Spain,European Euro,...,Easy,Too short,No,"Another engineering discipline (such as civil,...",Spring,Angular.js;Spring,Just as welcome now as I felt last year,50.0,22,17
20,21,I am a student who is learning to code,Yes,23.0,16,NaN,NaN,NaN,Belgium,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Gatsby;React.js;Spring;Vue.js,Angular;ASP.NET Core;Express;React.js;Spring,NaN,NaN,7,NaN
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
22,23,I am a developer by profession,Yes,27.0,14,NaN,NaN,NaN,Germany,European Euro,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Somewhat less welcome now than last year,40.0,8,3
23,24,I am a developer by profession,Yes,45.0,14,Yearly,85000.0,91883.0,Germany,European Euro,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,42.0,30,20
24,25,I am a developer by profession,No,NaN,25,Monthly,NaN,NaN,Portugal,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,23,18
25,26,I am a developer by profession,No,NaN,12,Yearly,94000.0,71093.0,Canada,Canadian dollar,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",NaN,Django;React.js,Just as welcome now as I felt last year,40.0,17,10
26,27,"I used to be a developer by profession, but no...",Yes,NaN,12,NaN,NaN,NaN,United States,NaN,...,Easy,Appropriate in length,No,"A humanities discipline (such as literature, h...",Flask,Flask,Just as welcome now as I felt last year,NaN,20,20
27,28,I am a student who is learning to code,Yes,NaN,22,NaN,NaN,NaN,China,NaN,...,Neither easy nor difficult,Too long,No,"A health science (such as nursing, pharmacy, r...",NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
28,29,I am a student who is learning to code,Yes,18.0,15,NaN,NaN,NaN,Ukraine,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery...,NaN,Not applicable - I did not use Stack Overflow ...,NaN,Less than 1 year,NaN
29,30,I am a developer by profession,Yes,NaN,14,Yearly,30000.0,38778.0,United Kingdom,Pound sterling,...,Neither easy nor difficult,Too long,No,"Information systems, information technology, o...",Express;React.js;Vue.js,Express;Vue.js,A lot less welcome now than last year,37.0,4,2
30,31,I am a developer by profession,Yes,NaN,20,Weekly,NaN,NaN,Russian Federation,Australian dollar,...,Easy,Appropriate in length,Yes,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,6,3
31,32,I am a developer by profession,Yes,31.0,12,Monthly,3500.0,31764.0,Canada,Canadian dollar,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,37.0,19,10
32,33,I am a developer by profession,Yes,39.0,14,Monthly,4900.0,63564.0,Belgium,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js;Ruby on Rails,Angular;Angular.js;Django;Express;React.js,Just as welcome now as I felt last year,40.0,20,14
33,34,I am a developer by profession,Yes,29.0,15,NaN,NaN,NaN,Germany,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Express;React.js;Spring,Angular;Express,Somewhat more welcome now than last year,NaN,10,NaN
34,35,I am a student who is learning to code,Yes,16.0,13,NaN,NaN,NaN,United States,NaN,...,Easy,Too long,No,"Information systems, information technology, o...",Angular;Angular.js;Express;jQuery;React.js;Vue.js,Express;jQuery,Just as welcome now as I felt last year,NaN,3,NaN
35,36,"I am not primarily a developer, but I write co...",Yes,34.0,30,Yearly,60000.0,77556.0,United Kingdom,Pound sterling,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;React.js,Express;React.js,Just as welcome now as I felt last year,40.0,4,3
36,37,I am a developer by profession,Yes,19.0,16,Monthly,NaN,NaN,France,European Euro,...,Easy,Too long,No,Web development or web design,Gatsby,Express;jQuery;React.js;Vue.js,Somewhat more welcome now than last year,39.0,2,1
37,38,I am a developer by profession,No,35.0,14,Yearly,90000.0,97288.0,Italy,European Euro,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js,Express;Gatsby;React.js,Just as welcome now as I felt last year,40.0,20,12
38,39,"I am not primarily a developer, but I write co...",Yes,NaN,17,NaN,NaN,NaN,United Kingdom,Pound sterling,...,Easy,Appropriate in length,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,13,1
39,40,I am a student who is learning to code,Yes,20.0,14,NaN,NaN,NaN,United States,NaN,...,Easy,Appropriate in length,No,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,6,NaN
40,41,I am a developer by profession,No,NaN,15,Yearly,106000.0,106000.0,United States,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",Vue.js,ASP.NET;Vue.js,A lot less welcome now than last year,40.0,25,20
41,42,I am a developer by profession,No,32.0,14,Yearly,130000.0,130000.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Spring,ASP.NET;Flask;React.js;Spring,Somewhat less welcome now than last year,37.0,16,10
42,43,I am a developer by profession,Yes,NaN,16,Yearly,135000.0,135000.0,United States,United States dollar,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,ASP.NET,Just as welcome now as I felt last year,45.0,36,29
43,44,I am a developer by profession,No,32.0,21,Yearly,244000.0,55893.0,Brazil,Brazilian real,...,Neither easy nor difficult,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,45.0,10,6
44,45,I am a developer by profession,Yes,22.0,13,Yearly,34000.0,36753.0,France,European Euro,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",Angular;Flask,Angular;Flask;jQuery;Spring,A lot less welcome now than last year,35.0,9,2
45,46,I am a developer by profession,Yes,24.0,14,Yearly,35000.0,37834.0,France,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,35.0,6,4
46,47,I am a developer by profession,Yes,53.0,10,Yearly,58000.0,74970.0,United Kingdom,Pound sterling,...,Neither easy nor difficult,Appropriate in length,No,"A natural science (such as biology, chemistry,...",Flask;Spring,Flask;Spring,Just as welcome now as I felt last year,40.0,43,28
47,48,I am a developer by profession,No,38.0,30,Yearly,125000.0,125000.0,United States,United States dollar,...,Easy,Appropriate in length,No,Fine arts or performing arts (such as graphic ...,Gatsby;Ruby on Rails,Gatsby;Ruby on Rails,NaN,30.0,8,8
48,49,I am a developer by profession,No,23.0,15,Yearly,52000.0,52000.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,40.0,8,4
49,50,I am a developer by profession,No,57.0,46,NaN,NaN,NaN,Austria,European Euro,...,Neither easy nor difficult,Too long,No,Fine arts or performing arts (such as graphic ...,jQuery,jQuery,Just as welcome now as I felt last year,35.0,10,9

In [5]:
df.size

3932121

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Respondent                    64461 non-null  int64
 1   MainBranch                    64162 non-null  object
 2   Hobbyist                      64416 non-null  object
 3   Age                           45446 non-null  float64
 4   Age1stCode                    57900 non-null  object
 5   CompFreq                      40069 non-null  object
 6   CompTotal                     34826 non-null  float64
 7   ConvertedComp                 34756 non-null  float64
 8   Country                       64072 non-null  object
 9   CurrencyDesc                  45472 non-null  object
 10  CurrencySymbol                45472 non-null  object
 11  DatabaseDesireNextYear        44070 non-null  object
 12  DatabaseWorkedWith            49537 non-null  object
 13  DevType                       49370 non-null  object
 14  EdLevel                       57431 non-null  object
 15  Employment                    63854 non-null  object
 16  Ethnicity                     45948 non-null  object
 17  Gender                        50557 non-null  object
 18  JobFactors                    49349 non-null  object
 19  JobSat                        45194 non-null  object
 20  JobSeek                       51727 non-null  object
 21  LanguageDesireNextYear        54113 non-null  object
 22  LanguageWorkedWith            57378 non-null  object
 23  MiscTechDesireNextYear        42379 non-null  object
 24  MiscTechWorkedWith            40314 non-null  object
 25  NEWCollabToolsDesireNextYear  47287 non-null  object
 26  NEWCollabToolsWorkedWith      52883 non-null  object
 27  NEWDevOps                     42686 non-null  object
 28  NEWDevOpsImpt                 41732 non-null  object
 29  NEWEdImpt                     48465 non-null  object
 30  NEWJobHunt                    42286 non-null  object
 31  NEWJobHuntResearch            41022 non-null  object
 32  NEWLearn                      56156 non-null  object
 33  NEWOffTopic                   50804 non-null  object
 34  NEWOnboardGood                42623 non-null  object
 35  NEWOtherComms                 57205 non-null  object
 36  NEWOvertime                   43231 non-null  object
 37  NEWPurchaseResearch           37321 non-null  object
 38  NEWPurpleLink                 54803 non-null  object
 39  NEWSOSites                    58275 non-null  object
 40  NEWStuck                      54983 non-null  object
 41  OpSys                         56228 non-null  object
 42  OrgSize                       44334 non-null  object
 43  PlatformDesireNextYear        50605 non-null  object
 44  PlatformWorkedWith            53843 non-null  object
 45  PurchaseWhat                  39364 non-null  object
 46  Sexuality                     43992 non-null  object
 47  SOAccount                     56805 non-null  object
 48  SOComm                        56476 non-null  object
 49  SOPartFreq                    46792 non-null  object
 50  SOVisitFreq                   56970 non-null  object
 51  SurveyEase                    51802 non-null  object
 52  SurveyLength                  51701 non-null  object
 53  Trans                         49345 non-null  object
 54  UndergradMajor                50995 non-null  object
 55  WebframeDesireNextYear        40024 non-null  object
 56  WebframeWorkedWith            42279 non-null  object
 57  WelcomeChange                 52683 non-null  object
 58  WorkWeekHrs                   41151 non-null  float64
 59  YearsCode                     57684 non-null  object
 60  YearsCodePro                  46349 non-null  object
dtypes: float64(4), int64(1), object(56)
memory usage: 16.2+ MB

In [7]:
df_1 = pd.read_csv(path, usecols=['MainBranch','Age','Gender','Country','DatabaseDesireNextYear','DatabaseWorkedWith',
                                 'LanguageDesireNextYear','LanguageWorkedWith','WebframeDesireNextYear'],)

In [8]:
df_1.head(100)

,MainBranch,Age,Country,DatabaseDesireNextYear,DatabaseWorkedWith,Gender,LanguageDesireNextYear,LanguageWorkedWith,WebframeDesireNextYear
0,I am a developer by profession,NaN,Germany,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,Man,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,ASP.NET Core
1,I am a developer by profession,NaN,United Kingdom,NaN,NaN,NaN,Python;Swift,JavaScript;Swift,NaN
2,I code primarily as a hobby,NaN,Russian Federation,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN
3,I am a developer by profession,25.0,Albania,NaN,NaN,Man,NaN,NaN,NaN
4,"I used to be a developer by profession, but no...",31.0,United States,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,Man,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Django;Ruby on Rails
...,...,...,...,...,...,...,...,...,...
95,I am a developer by profession,30.0,Canada,NaN,Cassandra;Elasticsearch,Woman,Bash/Shell/PowerShell;Go;Java;Rust,Bash/Shell/PowerShell;Go;Java;JavaScript;Rust;...,NaN
96,I am a developer by profession,29.0,Czech Republic,NaN,NaN,Man,C++;Python,C++;Python,NaN
97,I am a developer by profession,30.0,Canada,NaN,Elasticsearch;MongoDB,NaN,Python;TypeScript,Go;JavaScript;Python;SQL;TypeScript,NaN
98,I am a developer by profession,42.0,United States,NaN,MySQL,"Man;Non-binary, genderqueer, or gender non-con...",C#;JavaScript,C#;HTML/CSS;JavaScript;SQL,jQuery
99,I am a developer by profession,55.0,United States,MySQL;SQLite,MySQL;SQLite,Woman,HTML/CSS;JavaScript;PHP;SQL,HTML/CSS;JavaScript;PHP;SQL,NaN

In [9]:
df_1 = pd.read_csv(path, header=None, seq
                   usecols=['MainBranch','Age','Gender','Country','DatabaseDesireNextYear','DatabaseWorkedWith',
                            'LanguageDesireNextYear','LanguageWorkedWith','WebframeDesireNextYear'])

SyntaxError: invalid syntax (<ipython-input-9-520f5a60a818>, line 2)

In [ ]:
len(['MainBranch','Age','Gender','Country','DatabaseDesireNextYear','DatabaseWorkedWith',
                            'LanguageDesireNextYear','LanguageWorkedWith','WebframeDesireNextYear'])

In [ ]:
pd.set_option('display.max_columns',85) # This line will tell pandas to view every time 85 columns insted of showing
                                        # starting and ending 4 columns
pd.set_option('display.max_raws',85)    # This line is for showing 85 raws

In [ ]:
s = 'DatabaseDesireNextYear' 
d = 'DatabaseWorkedWith'
df.loc[:,d]